#!/bin/bash

envsubst < application/frontend.yaml.in > application/frontend.yaml
envsubst < application/database.yaml.in > application/database.yaml

envsubst < frontend/ingress.yaml.in > frontend/ingress.yaml
