#!/bin/bash

cd /opt/app-root

if [ x"$HOMEROOM_LINK" != x"" ]; then
    export AUDIENCE_LINK=$HOMEROOM_LINK
else
    if [ x"$WORKSHOP_LINK" != x"" ]; then
        export AUDIENCE_LINK=$WORKSHOP_LINK
    else
        if [ x"$JUPYTERHUB_ROUTE" != "" ]; then
            export AUDIENCE_LINK=$JUPYTERHUB_ROUTE
        else
            export AUDIENCE_LINK="???"
        fi
    fi
fi

envsubst < workshop/slides/notice.md.in > workshop/slides/notice.md

cd /opt/app-root/src

envsubst < frontend/ingress.yaml.in > frontend/ingress.yaml

envsubst < frontend-v3/ingress.yaml.in > frontend-v3/ingress.yaml
envsubst < frontend-v4/ingress.yaml.in > frontend-v4/ingress.yaml
envsubst < frontend-v5/ingress.yaml.in > frontend-v5/ingress.yaml
